# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lZ63Aa3kyVAcFGHC5YiXfAKPzOUCBZQO
"""

import pandas as pd
import numpy as np

# Load raw datasets again
prod_df = pd.read_csv("crop_production.csv")
geo_df = pd.read_csv("CropDataset-Enhanced.csv")

print("Raw Production Shape:", prod_df.shape)
print("Raw Geo Shape:", geo_df.shape)

# Keep only Maharashtra
prod_df = prod_df[prod_df["State_Name"] == "Maharashtra"].copy()

print("After Maharashtra Filter:", prod_df.shape)

# Clean district names
prod_df["District"] = (
    prod_df["District_Name"]
    .str.lower()
    .str.strip()
)

# Clean crop names
prod_df["Crop"] = (
    prod_df["Crop"]
    .str.lower()
    .str.strip()
)

# Clean district names in geo dataset
geo_df["District"] = (
    geo_df["Address"]
    .str.lower()
    .str.replace(", maharashtra", "", regex=False)
    .str.strip()
)

# Keep only Maharashtra geo rows
geo_df = geo_df[geo_df["Region"] == "Maharashtra"].copy()

geo_cols = [
    "District",
    "Latitude",
    "Longitude",
    "Nitrogen - High",
    "Nitrogen - Medium",
    "Nitrogen - Low",
    "Phosphorous - High",
    "Phosphorous - Medium",
    "Phosphorous - Low",
    "Potassium - High",
    "Potassium - Medium",
    "Potassium - Low",
    "pH - Acidic",
    "pH - Neutral",
    "pH - Alkaline"
]

geo_clean = geo_df[geo_cols].drop_duplicates(subset=["District"]).copy()

merged_df = pd.merge(
    prod_df,
    geo_clean,
    on="District",
    how="inner"
)

print("Merged Shape:", merged_df.shape)

soil_percent_cols = [
    "Nitrogen - High",
    "Nitrogen - Medium",
    "Nitrogen - Low",
    "Phosphorous - High",
    "Phosphorous - Medium",
    "Phosphorous - Low",
    "Potassium - High",
    "Potassium - Medium",
    "Potassium - Low",
    "pH - Acidic",
    "pH - Neutral",
    "pH - Alkaline"
]

for col in soil_percent_cols:
    merged_df[col] = (
        merged_df[col]
        .astype(str)
        .str.replace("%", "", regex=False)
        .astype(float)
    )

merged_df["Nitrogen_Score"] = (
    merged_df["Nitrogen - High"] * 3 +
    merged_df["Nitrogen - Medium"] * 2 +
    merged_df["Nitrogen - Low"] * 1
)

merged_df["Phosphorous_Score"] = (
    merged_df["Phosphorous - High"] * 3 +
    merged_df["Phosphorous - Medium"] * 2 +
    merged_df["Phosphorous - Low"] * 1
)

merged_df["Potassium_Score"] = (
    merged_df["Potassium - High"] * 3 +
    merged_df["Potassium - Medium"] * 2 +
    merged_df["Potassium - Low"] * 1
)

# Yield calculation
merged_df["Yield"] = merged_df["Production"] / merged_df["Area"]

# Remove infinite or NaN
merged_df = merged_df.replace([np.inf, -np.inf], 0)
merged_df = merged_df.dropna()

best_crop_df = merged_df.loc[
    merged_df.groupby("District")["Production"].idxmax()
].copy()

print("Final District Count:", best_crop_df.shape[0])

# Save full cleaned dataset
merged_df.to_csv("BhooDristi_cleaned_full_dataset.csv", index=False)

# Save district-level dataset
best_crop_df.to_csv("BhooDristi_district_dataset.csv", index=False)

print("Cleaned datasets saved successfully.")

import pandas as pd

best_crop_df = pd.read_csv("BhooDristi_district_dataset.csv")

print(best_crop_df.shape)
best_crop_df.head()

features = [
    "Nitrogen_Score",
    "Phosphorous_Score",
    "Potassium_Score",
    "pH - Acidic",
    "pH - Neutral",
    "pH - Alkaline",
    "Latitude",
    "Longitude"
]

X = best_crop_df[features]
y = best_crop_df["Crop"]

print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

print("Train size:", X_train.shape)
print("Test size:", X_test.shape)

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

models = {
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "SVM": SVC(probability=True)
}

results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    results[name] = acc

results

import pandas as pd

results_df = pd.DataFrame(results.items(), columns=["Model", "Accuracy"])
results_df.sort_values(by="Accuracy", ascending=False)

from sklearn.model_selection import cross_val_score

cv_results = {}

for name, model in models.items():
    scores = cross_val_score(model, X, y, cv=5)
    cv_results[name] = scores.mean()

pd.DataFrame(cv_results.items(), columns=["Model", "CV Accuracy"]).sort_values(by="CV Accuracy", ascending=False)

from sklearn.ensemble import GradientBoostingClassifier
import joblib

features = [
    "Nitrogen_Score",
    "Phosphorous_Score",
    "Potassium_Score",
    "pH - Acidic",
    "pH - Neutral",
    "pH - Alkaline",
    "Latitude",
    "Longitude"
]

X = best_crop_df[features]
y = best_crop_df["Crop"]

gb_model = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

gb_model.fit(X, y)

print("Final Gradient Boosting model trained successfully.")

joblib.dump(gb_model, "BhooDristi_gb_model.pkl")
print("Model saved successfully.")

joblib.dump(features, "BhooDristi_features.pkl")
print("Feature list saved successfully.")

joblib.dump(gb_model.classes_, "BhooDristi_classes.pkl")

from google.colab import files

files.download("BhooDristi_gb_model.pkl")
files.download("BhooDristi_features.pkl")
files.download("BhooDristi_classes.pkl")

import joblib
import pandas as pd

# Load saved model
model = joblib.load("BhooDristi_gb_model.pkl")

# Load feature list
feature_columns = joblib.load("BhooDristi_features.pkl")

# Load cleaned district dataset
best_crop_df = pd.read_csv("BhooDristi_district_dataset.csv")

# Create district lookup table
district_features = best_crop_df.set_index("District")

print("Production environment ready.")

def BhooDristi_predict(district_name):

    district_name = district_name.lower().strip()

    # Check district existence
    if district_name not in district_features.index:
        return {
            "Error": "District not found in BhooDristi database."
        }

    # Extract district row
    row = district_features.loc[district_name]

    # Prepare model input
    input_data = pd.DataFrame([[
        row["Nitrogen_Score"],
        row["Phosphorous_Score"],
        row["Potassium_Score"],
        row["pH - Acidic"],
        row["pH - Neutral"],
        row["pH - Alkaline"],
        row["Latitude"],
        row["Longitude"]
    ]], columns=feature_columns)

    # Make prediction
    predicted_crop = model.predict(input_data)[0]
    probabilities = model.predict_proba(input_data)[0]

    # Confidence
    confidence = float(round(max(probabilities) * 100, 2))

    # Top 3 recommendations
    classes = model.classes_
    top3_idx = probabilities.argsort()[-3:][::-1]

    top3 = []
    for idx in top3_idx:
        top3.append({
            "Crop": classes[idx],
            "Confidence (%)": float(round(probabilities[idx] * 100, 2))
        })

    # Final output (API-ready JSON format)
    return {
        "District": district_name.title(),
        "Primary Recommendation": predicted_crop,
        "Confidence (%)": confidence,
        "Top 3 Recommendations": top3
    }

BhooDristi_predict("akola")

import pandas as pd

merged_df = pd.read_csv("BhooDristi_cleaned_full_dataset.csv")

print("Dataset Shape:", merged_df.shape)
merged_df.head()

features = [
    "Nitrogen_Score",
    "Phosphorous_Score",
    "Potassium_Score",
    "pH - Acidic",
    "pH - Neutral",
    "pH - Alkaline",
    "Latitude",
    "Longitude"
]

X = merged_df[features]
y = merged_df["Crop"]

print("Feature shape:", X.shape)
print("Unique crops:", y.nunique())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Train size:", X_train.shape)
print("Test size:", X_test.shape)

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score

gb_model = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

gb_model.fit(X_train, y_train)

y_pred = gb_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Test Accuracy:", accuracy)

from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(gb_model, X, y, cv=5)
print("Cross Validation Accuracy:", cv_scores.mean())

from sklearn.preprocessing import LabelEncoder

le_season = LabelEncoder()
merged_df["Season_Encoded"] = le_season.fit_transform(merged_df["Season"])

features = [
    "Nitrogen_Score",
    "Phosphorous_Score",
    "Potassium_Score",
    "pH - Acidic",
    "pH - Neutral",
    "pH - Alkaline",
    "Latitude",
    "Longitude",
    "Season_Encoded"   # NEW
]

X = merged_df[features]
y = merged_df["Crop"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

gb_model = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

gb_model.fit(X_train, y_train)

print("Test Accuracy:", accuracy_score(y_test, gb_model.predict(X_test)))

merged_df["Crop"].nunique()

features = [
    "Nitrogen_Score",
    "Phosphorous_Score",
    "Potassium_Score",
    "pH - Acidic",
    "pH - Neutral",
    "pH - Alkaline",
    "Latitude",
    "Longitude",
    "Season_Encoded"
]

y = merged_df["Crop"]

import numpy as np

probs = gb_model.predict_proba(X_test)
classes = gb_model.classes_

top3_correct = 0

for i in range(len(y_test)):
    top3_indices = np.argsort(probs[i])[-3:]
    top3_classes = classes[top3_indices]

    if y_test.iloc[i] in top3_classes:
        top3_correct += 1

top3_accuracy = top3_correct / len(y_test)

print("Top-3 Accuracy:", top3_accuracy)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import numpy as np

# Features (with season included)
features = [
    "Nitrogen_Score",
    "Phosphorous_Score",
    "Potassium_Score",
    "pH - Acidic",
    "pH - Neutral",
    "pH - Alkaline",
    "Latitude",
    "Longitude",
    "Season_Encoded"
]

X = merged_df[features]
y = merged_df["Crop"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Train Random Forest
rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

# Standard accuracy
y_pred = rf_model.predict(X_test)
print("RF Test Accuracy:", accuracy_score(y_test, y_pred))

probs = rf_model.predict_proba(X_test)
classes = rf_model.classes_

top3_correct = 0

for i in range(len(y_test)):
    top3_indices = np.argsort(probs[i])[-3:]
    top3_classes = classes[top3_indices]

    if y_test.iloc[i] in top3_classes:
        top3_correct += 1

top3_accuracy = top3_correct / len(y_test)

print("RF Top-3 Accuracy:", top3_accuracy)

import pandas as pd

# Load crop recommendation dataset
crop_df = pd.read_csv("CropDataset-Enhanced.csv")

print(crop_df.shape)
crop_df.head()

import pandas as pd

# Load crop recommendation dataset
crop_df = pd.read_csv("crop_production.csv")

print(crop_df.shape)
crop_df.head()

import pandas as pd

crop_df = pd.read_csv("Crop_recommendation.csv")

print(crop_df.shape)
crop_df.head()

import pandas as pd

# Load dataset
crop_df = pd.read_csv("Crop_recommendation.csv")

# Define features and target
features = ["N", "P", "K", "temperature", "humidity", "ph", "rainfall"]

X = crop_df[features]
y = crop_df["label"]

print("Dataset shape:", crop_df.shape)
print("Unique crops:", y.nunique())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf_model = RandomForestClassifier(
    n_estimators=400,
    random_state=42
)

rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_pred))

import numpy as np

def BhooDristi_recommend(N, P, K, temperature, humidity, ph, rainfall):

    input_data = pd.DataFrame([[
        N, P, K, temperature, humidity, ph, rainfall
    ]], columns=features)

    probs = rf_model.predict_proba(input_data)[0]
    classes = rf_model.classes_

    top3_idx = np.argsort(probs)[-3:][::-1]

    recommendations = []
    for idx in top3_idx:
        recommendations.append({
            "Crop": classes[idx],
            "Confidence (%)": round(probs[idx] * 100, 2)
        })

    return recommendations

BhooDristi_recommend(
    N=90,
    P=42,
    K=43,
    temperature=21,
    humidity=80,
    ph=6.5,
    rainfall=200
)

import joblib

# Save model
joblib.dump(rf_model, "BhooDristi_model_final.pkl")

# Save feature list
joblib.dump(features, "BhooDristi_features_final.pkl")

print("Model saved successfully.")

from google.colab import files

files.download("BhooDristi_model_final.pkl")
files.download("BhooDristi_features_final.pkl")

## EXECUTE FROM HERE

import joblib
import pandas as pd
import numpy as np

# Load model
rf_model = joblib.load("BhooDristi_model_final.pkl")

# Load feature list
features = joblib.load("BhooDristi_features_final.pkl")

print("Model loaded successfully.")

import joblib

rf_model = joblib.load("BhooDristi_model_final.pkl")
features = joblib.load("BhooDristi_features_final.pkl")

import shap

explainer = shap.TreeExplainer(rf_model)

import pandas as pd

input_data = pd.DataFrame([[
    90, 42, 43, 21, 80, 6.5, 200
]], columns=features)

shap_values = explainer.shap_values(input_data)

import numpy as np

prediction = rf_model.predict(input_data)[0]
class_index = list(rf_model.classes_).index(prediction)

print("Predicted Crop:", prediction)

shap_contrib = shap_values[0, :, class_index]

shap_df = pd.DataFrame({
    "Feature": features,
    "SHAP Contribution": shap_contrib
}).sort_values(by="SHAP Contribution", key=abs, ascending=False)

shap_df

feature_explanations = {
    "N": "Nitrogen levels support strong vegetative crop growth.",
    "P": "Phosphorus improves root development and early crop growth.",
    "K": "Potassium improves crop resistance and overall plant health.",
    "temperature": "The temperature range is suitable for crop growth.",
    "humidity": "Humidity levels support proper crop moisture conditions.",
    "ph": "Soil pH is within the suitable range for nutrient absorption.",
    "rainfall": "Rainfall levels support water-demanding crops."
}

crop_knowledge = {



"rice":"Rice thrives in high rainfall and humid environments with good nitrogen availability.",
"maize":"Maize grows well in warm temperatures with moderate rainfall.",
"wheat":"Wheat prefers moderate temperature and well-drained soils.",
"cotton":"Cotton grows best in warm climates with moderate rainfall.",
"sugarcane":"Sugarcane requires high water availability and fertile soil.",
"jute":"Jute grows well in warm humid climates with high rainfall.",
"coffee":"Coffee prefers mild temperature and high rainfall.",
"banana":"Banana requires warm temperatures and high humidity.",
"mango":"Mango grows well in warm tropical climates.",
"pomegranate":"Pomegranate grows well in dry climates with well-drained soil.",
"lentil":"Lentils grow well in cool dry climates.",
"mungbean":"Mungbean grows well in warm climates with moderate rainfall.",
"blackgram":"Black gram grows well in warm regions.",
"chickpea":"Chickpea grows well in cooler climates.",
"kidneybeans":"Kidney beans prefer moderate temperatures.",
"pigeonpeas":"Pigeon peas tolerate drought conditions.",
"mothbeans":"Moth beans grow well in arid climates.",
"millet":"Millets are drought resistant crops.",
"watermelon":"Watermelon grows well in warm climates with moderate irrigation.",
"muskmelon":"Muskmelon prefers warm climates.",
"grapes":"Grapes grow well in warm dry climates.",
"apple":"Apple trees grow best in cooler climates.",
"papaya":"Papaya grows well in warm climates with moderate rainfall and fertile soil."
}

import pandas as pd

geo_df = pd.read_csv("CropDataset-Enhanced.csv")

geo_df.head()

geo_df.columns

import re

def clean_percent(x):
    x = str(x)

    # find first percentage value like 0.05%
    match = re.search(r'\d+\.?\d*%', x)

    if match:
        return float(match.group().replace('%',''))
    else:
        return 0.0

geo_df["Nitrogen - High"] = geo_df["Nitrogen - High"].apply(clean_percent)
geo_df["Phosphorous - High"] = geo_df["Phosphorous - High"].apply(clean_percent)
geo_df["Potassium - High"] = geo_df["Potassium - High"].apply(clean_percent)
geo_df["pH - Neutral"] = geo_df["pH - Neutral"].apply(clean_percent)

district_soil = geo_df.copy()

district_soil["District"] = district_soil["Address"].str.lower().str.strip()

district_soil = district_soil[[
    "District",
    "Nitrogen - High",
    "Phosphorous - High",
    "Potassium - High",
    "pH - Neutral"
]]

district_soil["N"] = district_soil["Nitrogen - High"]
district_soil["P"] = district_soil["Phosphorous - High"]
district_soil["K"] = district_soil["Potassium - High"]
district_soil["ph"] = 6.5

season_crops = {
    "kharif": [
        # Primary crops
        "rice","maize","cotton","sugarcane",
        # Pulses
        "pigeonpeas", "pigeonpea", "mungbean", "mung", "blackgram", "urid", 
        "mothbeans", "groundnut",
        # Other
        "jowar", "sorghum", "soybeans", "soybean"
    ],
    "rabi": [
        # Primary crops
        "wheat","chickpea","chick pea","gram","lentil","lentils",
        "barley", "oats",
        # Oilseeds
        "mustard", "rapeseed", "sunflower",
        # Vegetables
        "onion", "garlic", "peas", "pea",
        # Others
        "sugarcane", "jowar", "sorghum", "maize"
    ],
    "zaid": [
        # Summer vegetables
        "watermelon", "muskmelon", "cucumber", "squash", 
        "pumpkin", "bottlegourd", "bottle gourd", "cowpea", "okra", "brinjal"
    ]
}

crop_knowledge = {
    "rice": "Rice thrives in high rainfall and humid environments.",
    "maize": "Maize grows well in warm climates with moderate rainfall.",
    "cotton": "Cotton requires warm temperatures and well-drained soil.",
    "pigeonpeas": "Pigeon pea grows well in semi-arid conditions.",
    "wheat": "Wheat prefers cool temperatures and moderate rainfall.",
    "chickpea": "Chickpea grows best in dry and cool climates.",
    "watermelon": "Watermelon requires warm temperatures and moderate irrigation.",
    "banana": "Banana grows best in humid tropical climates."
}

import pandas as pd
import numpy as np

def predict_by_district(district, season):

    district = district.lower().strip()
    season = season.lower().strip()

    # Validate district
    if district not in district_soil["District"].values:
        return {"Error": "District not found"}

    # Get soil values
    soil = district_soil[district_soil["District"] == district].iloc[0]

    N = float(soil["N"])
    P = float(soil["P"])
    K = float(soil["K"])
    ph = float(soil["ph"])

    # Seasonal weather defaults
    weather_defaults = {
        "kharif": {"temperature": 28, "humidity": 80, "rainfall": 200},
        "rabi": {"temperature": 22, "humidity": 60, "rainfall": 50},
        "zaid": {"temperature": 34, "humidity": 40, "rainfall": 20}
    }

    if season not in weather_defaults:
        return {"Error": "Invalid season"}

    weather = weather_defaults[season]

    temperature = weather["temperature"]
    humidity = weather["humidity"]
    rainfall = weather["rainfall"]

    # Prepare model input
    input_data = pd.DataFrame(
        [[N, P, K, temperature, humidity, ph, rainfall]],
        columns=features
    )

    # Predict probabilities
    probs = rf_model.predict_proba(input_data)[0]
    classes = rf_model.classes_

    # Filter crops by season
    allowed = season_crops.get(season, [])

    filtered = []

    for i in probs.argsort()[::-1]:
        crop = classes[i]

        if crop in allowed:
            filtered.append((crop, probs[i]))

        if len(filtered) == 3:
            break

    if len(filtered) == 0:
        return {"Error": "No suitable crops found"}

    # Normalize probabilities
    prob_sum = sum(p for _, p in filtered)

    recommendations = []
    for crop, prob in filtered:

        normalized = (prob / prob_sum) * 100

        recommendations.append({
            "Crop": crop,
            "Confidence (%)": round(float(normalized),2)
        })

    best_crop = recommendations[0]["Crop"]
    confidence = recommendations[0]["Confidence (%)"]

    # SHAP Explanation
    shap_values = explainer.shap_values(input_data)

    class_index = list(classes).index(best_crop)

    shap_contrib = shap_values[0,:,class_index]

    shap_df = pd.DataFrame({
        "Feature": features,
        "Contribution": shap_contrib
    }).sort_values(by="Contribution", key=abs, ascending=False)

    top_features = shap_df.head(3)

    explanations = []

    for _, row in top_features.iterrows():

        feature = row["Feature"]

        explanations.append(
            feature_explanations.get(
                feature,
                f"{feature} influenced the recommendation."
            )
        )

    return {
        "District": district.title(),
        "Season": season.title(),
        "Recommended Crop": best_crop,
        "Confidence (%)": confidence,
        "Top 3 Crops": recommendations,
        "Agronomic Insight": crop_knowledge.get(best_crop, ""),
        "Key Factors": explanations
    }

predict_by_district("akola","kharif")

def get_coordinates(district):

    row = geo_df[geo_df["District"] == district.lower()].iloc[0]

    lat = row["Latitude"]
    lon = row["Longitude"]

    return lat, lon

import requests
import os

API_KEY = os.getenv("OPENWEATHERMAP_API_KEY", "your_api_key")

def get_weather(lat, lon):

    url = f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&units=metric&appid={API_KEY}"

    data = requests.get(url).json()

    temperature = data["main"]["temp"]
    humidity = data["main"]["humidity"]

    rainfall = 0
    if "rain" in data:
        rainfall = data["rain"].get("1h", 0)

    return temperature, humidity, rainfall

def get_soil(district):

    row = district_soil[district_soil["District"] == district.lower()].iloc[0]

    N = row["N"]
    P = row["P"]
    K = row["K"]
    ph = row["ph"]

    return N, P, K, ph

def BhooDristi_predict(district):

    # Get coordinates
    lat, lon = get_coordinates(district)

    # Get weather
    temperature, humidity, rainfall = get_weather(lat, lon)

    # Get soil
    N, P, K, ph = get_soil(district)

    # Prepare input
    input_data = pd.DataFrame([[N,P,K,temperature,humidity,ph,rainfall]],
                              columns=features)

    probs = rf_model.predict_proba(input_data)[0]
    classes = rf_model.classes_

    idx = probs.argmax()

    crop = classes[idx]
    confidence = probs[idx]*100

    return {
        "District": district.title(),
        "Recommended Crop": crop,
        "Confidence (%)": round(confidence,2)
    }

import requests
import os

def get_weather(lat, lon):

    API_KEY = os.getenv("OPENWEATHERMAP_API_KEY", "your_api_key")

    url = f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={API_KEY}&units=metric"

    response = requests.get(url)
    data = response.json()

    # Safety check
    if "main" not in data:
        print("Weather API error:", data)
        return 28, 70, 120  # fallback values

    temperature = data["main"]["temp"]
    humidity = data["main"]["humidity"]
    rainfall = data.get("rain", {}).get("1h", 100)

    return temperature, humidity, rainfall

lat, lon = get_coordinates("akola")

get_weather(lat, lon)

print(geo_df.columns)

print(district_soil.columns)

geo_df["District"] = geo_df["Address"].str.lower().str.strip()

geo_df[["District","Latitude","Longitude"]].head()

print(geo_df["District"].unique()[:10])
print(district_soil["District"].unique()[:10])

geo_df["District"] = geo_df["District"].str.replace(", maharashtra","", regex=False)
district_soil["District"] = district_soil["District"].str.replace(", maharashtra","", regex=False)

geo_df["District"] = geo_df["District"].str.strip()
district_soil["District"] = district_soil["District"].str.strip()

print(geo_df["District"].unique()[:10])

get_coordinates("akola")

get_soil("akola")

BhooDristi_predict("ratnagiri")

## Fully automatic function

from datetime import datetime

def BhooDristi_predict(district):

    import pandas as pd
    import numpy as np
    from datetime import datetime

    district = district.lower().strip()

    # ----------------------------
    # 1️⃣ Detect Season
    # ----------------------------
    month = datetime.now().month

    if month in [6,7,8,9,10]:
        season = "Kharif"
    elif month in [11,12,1,2,3]:
        season = "Rabi"
    else:
        season = "Zaid"


    # ----------------------------
    # 2️⃣ Get Coordinates
    # ----------------------------
    row = geo_df[geo_df["District"] == district]

    if row.empty:
        return {"Error": "District not found in geo dataset"}

    lat = row.iloc[0]["Latitude"]
    lon = row.iloc[0]["Longitude"]


    # ----------------------------
    # 3️⃣ Get Weather
    # ----------------------------
    temperature, humidity, rainfall = get_weather(lat, lon)


    # ----------------------------
    # 4️⃣ Get Soil Data
    # ----------------------------
    soil_row = district_soil[district_soil["District"] == district]

    if soil_row.empty:
        return {"Error": "District not found in soil dataset"}

    N = soil_row.iloc[0]["N"]
    P = soil_row.iloc[0]["P"]
    K = soil_row.iloc[0]["K"]
    ph = soil_row.iloc[0]["ph"]


    # ----------------------------
    # 5️⃣ Model Input
    # ----------------------------
    input_data = pd.DataFrame(
        [[N, P, K, temperature, humidity, ph, rainfall]],
        columns=["N","P","K","temperature","humidity","ph","rainfall"]
    )


    # ----------------------------
    # 6️⃣ Prediction
    # ----------------------------
    probs = model.predict_proba(input_data)[0]
    prediction = model.predict(input_data)[0]


    # ----------------------------
    # 7️⃣ Top 3 Crops
    # ----------------------------
    top_indices = np.argsort(probs)[-3:][::-1]

    top_crops = []

    for i in top_indices:
        top_crops.append({
            "Crop": label_encoder.classes_[i],
            "Confidence (%)": float(round(probs[i]*100,2))
        })


    # ----------------------------
    # 8️⃣ SHAP Explainability
    # ----------------------------
    shap_values = explainer.shap_values(input_data)

    class_index = list(model.classes_).index(prediction)

    # Correct SHAP extraction
    shap_contrib = shap_values[0][:, class_index]

    features = input_data.columns

    shap_df = pd.DataFrame({
        "Feature": features,
        "Impact": shap_contrib
    })

    shap_df = shap_df.reindex(
        shap_df.Impact.abs().sort_values(ascending=False).index
    )

    top_features = shap_df.head(3)


    # ----------------------------
    # 9️⃣ Farmer Friendly Explanation
    # ----------------------------
    feature_names = {
        "N":"Nitrogen levels",
        "P":"Phosphorus levels",
        "K":"Potassium levels",
        "temperature":"Temperature conditions",
        "humidity":"Humidity levels",
        "ph":"Soil pH",
        "rainfall":"Rainfall availability"
    }

    explanations = []

    for _, row in top_features.iterrows():

        feature = row["Feature"]

        explanations.append(
            f"{feature_names.get(feature, feature)} strongly influenced the crop recommendation."
        )


    # ----------------------------
    # 🔟 Final Output
    # ----------------------------
    return {

        "District": district.title(),

        "Detected Season": season,

        "Recommended Crop": prediction,

        "Confidence (%)": float(round(max(probs)*100,2)),

        "Top 3 Crops": top_crops,

        "Model Explanation": explanations
    }

def display_prediction(result):

    print("\n🌾 BhooDristi Crop Recommendation\n")

    print(f"District: {result['District']}")
    print(f"Season: {result['Detected Season']}\n")

    print(f"Recommended Crop: {result['Recommended Crop'].title()}")
    print(f"Confidence: {result['Confidence (%)']}%\n")

    print("Other Suitable Crops:")

    for i, crop in enumerate(result["Top 3 Crops"], 1):
        name = crop["Crop"].replace("kidneybeans","Kidney Beans")\
                           .replace("pigeonpeas","Pigeon Peas")\
                           .replace("mungbean","Mung Bean")\
                           .title()

        print(f"{i}. {name} ({crop['Confidence (%)']}%)")

    print("\nWhy this crop was recommended:\n")

    for reason in result["Model Explanation"]:
        print(f"• {reason}")

    print("\nAgronomic Insight:")

    insights = {
        "chickpea": "Chickpea performs well in moderate temperatures and well-drained soils during the Rabi season.",
        "rice": "Rice thrives in high rainfall regions with warm temperatures and good nitrogen availability.",
        "maize": "Maize grows best in warm climates with moderate rainfall and well-drained soils.",
        "cotton": "Cotton requires warm temperatures, moderate rainfall, and good sunlight exposure.",
        "sugarcane": "Sugarcane grows well in tropical climates with abundant water and fertile soil."
    }

    crop = result["Recommended Crop"]

    print(insights.get(crop, "This crop is suitable under the detected soil and weather conditions."))

result = BhooDristi_predict("akola")

display_prediction(result)

BhooDristi_predict("akola")

